### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by virpatel524** [pierpal/IBDMUT#1]
Hi,

I'm running IBDMUT on my malaria data, using IBD estimates based on hmmIBD and converting that data into the germline format. When running the program, I receive a NullPointerException as attached. I tried running the program with some of your example data and found no such issue. Any idea what might be at play?

[ibdmut_failure.txt](https://github.com/pierpal/IBDMUT/files/2150350/ibdmut_failure.txt)

**Comment by pierpal** [comment]
This happens at
                    BitSet bitSeq1 = ID1.getBitSeq();
Where
                    Individual ID1 = data.getIndividuals().get(FamID1 + "\t" + IndID1);
Likely returns null. The FamID and IndID come from the match file lines:
                    String FamID1 = strSplit[0];
                    String IndID1 = strSplit[1];
                    String FamID2 = strSplit[2];
                    String IndID2 = strSplit[3];
You may want to make sure the match file FamID and IndID are the same as in the input data.
